package:
  name: 'conjure'
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: .

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - jupyter
  run:
    - python
    - jupyter

test:
  imports:
    - conjure

about:
  home: https://github.com/conjure-cp/conjure-notebook
  license: The 3-Clause BSD License
  license_file: LICENSE
  summary: Conjure extension for Jupyter Notebooks
