on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install packages
        run: pip install jupyterlab

      - name: Get conjure
        run: |
            wget --quiet --no-check-certificate -c https://github.com/conjure-cp/conjure/releases/download/v2.4.0/conjure-v2.4.0-linux-with-solvers.zip
            unzip -q -o conjure-v2.4.0-linux-with-solvers.zip
            cp -r conjure-v2.4.0-linux-with-solvers/* /usr/local/bin

      - name: Install conjure-notebook
        run: pip install .

      - name: Run tests
        run: cd test && ./run_tests.sh
